### ISSUE TITLE
Head elements are not wrapped in a Head tag

### ISSUE THREAD

**Issue by nwehner** [syntax-tree/hast-util-to-html#14]
### Subject of the issue

Describe your issue here.

This is *not* a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/unified)

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by wooorm** [comment]
You did not fill in the issue template.

**Comment by nwehner** [comment]
Working on it! Github decided to save everything early when I accidentally tapped by yubikey.

**Comment by nwehner** [comment]
Ok finally done :)
