### ISSUE TITLE
Head elements are not wrapped in a Head tag

### ISSUE THREAD

**Issue by nwehner** [syntax-tree/hast-util-to-html#15]
### Subject of the issue

If this utility is run with a Hast-formatted HTML document containing a DocumentType, Head, and Body, the converted HTML is printed with the DocumentType, then the Body, and finally the contents of the Head are spit-out just before the closing Body tag without being wrapped in a Head tag. As a result, the generated HTML is invalid. 

### Your environment

*   **OS**: MacOS Mojave 10.14.6
*   **Packages**: hast-util-to-html@6.0.2
*   **Env**: Node v12.4.0, NPM 6.11.3

### Steps to reproduce

Provided with a minimal Hast object containing the HTML DocType, Head, and Body elements: 
`{
         type: 'element',
         tagName: 'html',
         children: [
            {
                 type: 'element',
                 tagName: 'head',
                 children: [headContent]
            },
             {
                 type: 'element',
                 tagName: 'body',
                 children: [bodyContent]
            },
         ]
}`

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour
`<html>`
`<head>headContent</head>`
`<body>bodyContent</body>`
`</html>`

### Actual behaviour
`<html>`
`<body>`
`bodyContent`
`headContent`
`</body>`
`</html>`

What happens instead?
The contents of the Head are not wrapped in a Head tag, and are spit-out just before the closing body tag.

**Comment by ChristianMurphy** [comment]
@nwehner can you clarify how the actual behavior is invalid?

Looking at the HTML spec
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head
https://html.spec.whatwg.org/multipage/semantics.html#the-head-element

It looks like

```html
<html>
<head>headContent</head>
<body>bodyContent</body>
</html>
```

would be invalid output.
Only `<title>`, `<link>`, `<base>`, `<script>`, `<meta>`, and other metadata tags are allowable content.
Text and paragraphs are not.

**Comment by nwehner** [comment]
I think you are mistaken: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html

The only valid syntax for HTML is 
`<html>`
`<head>metadata</head>`
`<body>content</body>`
`</html>`

**Comment by nwehner** [comment]
Note that the permitted content for HTML is:
> One <head> element, followed by one <body> element.

**Comment by ChristianMurphy** [comment]
again the literal text `metadata` used in the example, is not valid content for `<head>`, it must be actual metadata tags, not text.

---

> > Note that the permitted content for HTML is:
>
> One <head> element, followed by one <body> element.

The spec is a bit contradictory on this front, from the MDN docs on `<head>`:

> HTML5-compliant browsers automatically create a <head> element if its tags are omitted in the markup.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head#Notes

Meaning `<head>` is an optional tag.

**Comment by nwehner** [comment]
A) "metadata" is a placeholder. I know that's not valid content, thank you.
B) Regardless if something is optional, if the option is present, it should be handled appropriately.

**Comment by ChristianMurphy** [comment]
@nwehner here is an example of `<head>` and `<body>` working, as expected.

```js
var h = require('hastscript')
var toHtml = require("hast-util-to-html");

var tree = h('html', [
  h('head', [h('title', 'example')]),
  h('body', 'content')
])

toHtml(tree);
```

runnable version: https://runkit.com/embed/dfmvrvtvpe7g

---

Can you provide a runnable example of the issue you are seeing?

**Comment by nwehner** [comment]
Sure enough, as soon as I moved away from local to Cloud9 the issue wasn't around any more. Finally found the error was in an import statement, grabbing the wrong 'h' builder for the <head> elements. That'll do it! Sorry, everyone.
