### ISSUE TITLE
Circular dependencies breaks rollup and vite builds

### ISSUE THREAD

**Issue by gargakshit** [syntax-tree/hast-util-to-html#22]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.3

### Steps to reproduce

1. Use rollup for bundle project with this library as a dependency (or a peer dependency)
1. Build project and run it in a browser

### Expected behavior

It runs

### Actual behavior

Rollup (and by extension vite) doesn't bundle circular dependencies properly which results in the app failing during production builds.

Related issue: https://github.com/syntax-tree/mdast-util-to-hast/issues/55

### Runtime

Other (please specify in steps to reproduce)

### Package manager

yarn v1

### OS

Windows

### Build and bundle tools

Rollup, Vite

**Comment by wooorm** [comment]
I would suggest raising this as an issue with Rollup.
Alternatively, a PR to change this here would be accepted!

**Comment by wooorm** [comment]
@gargakshit @ZirionNeft Either of you interested in helping with this issue?

**Comment by ZirionNeft** [comment]
> @gargakshit @ZirionNeft Either of you interested in helping with this issue?

How may I help you?

**Comment by wooorm** [comment]
Hh whoops, the PR already landed, never mind!
