### ISSUE TITLE
Text is encoded even when setting allowDangerousCharacters/allowDangerousHtml

### ISSUE THREAD

**Issue by karellodewijk** [syntax-tree/hast-util-to-html#24]
### Affected packages and versions

8.0.2

### Steps to reproduce

```
import { toHtml } from 'hast-util-to-html';

let test = {
  "type": "element",
  "tagName": "text",
  "children": [
      {
          "type": "text",
          "value": "-&#xa;"
      }
  ]
}

console.log(toHtml(test, {allowDangerousCharacters: true, allowDangerousHtml: true}))

```

### Expected behavior

`<text>-&#xa;</text>`

### Actual behavior

`<text>-&#x26;#xa;</text>`

**Comment by wooorm** [comment]
BTW it’s not recommended to use such character references in XML. If you have any control over the input, I’d recommend to change it to the actual character (a line ending right?)
