### ISSUE TITLE
failed to compile ts code using hast-util-to-html

### ISSUE THREAD

**Issue by wataru-chocola** [syntax-tree/hast-util-to-html#25]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.2

### Steps to reproduce

Install `hast-util-to-html` on a new project.

```
$ npm install hast-util-to-html
```

Create `test.ts` file which just imports from `hast-util-to-html`,

```typescript
import { toHtml } from 'hast-util-to-html';
```

and compile it.

```
$ tsc test.ts
```

### Expected behavior

Run without errors.

### Actual behavior

Error occured.

```sh-sessoin
$ npx tsc a.ts
node_modules/hast-util-to-html/lib/types.d.ts:15:32 - error TS2694: Namespace '"/tmp/test_pjoject/node_modules/stringify-entities/index"' has no exported member 'StringifyEntitiesOptions'.

15   import('stringify-entities').StringifyEntitiesOptions
                                  ~~~~~~~~~~~~~~~~~~~~~~~~
```

### Runtime

Node v16

### Package manager

npm v7

**Comment by leafac** [comment]
Wow, what a huge coincidence! I just ran into this same issue!

**Comment by leafac** [comment]
The issue probably has to do with this release https://github.com/wooorm/stringify-entities/releases/tag/4.0.2, so as a temporary workaround:

```console
$ npm i stringify-entities@4.0.1
```

**Comment by wooorm** [comment]
You can do add a `skipLibCheck` field to your `tsconfig` to improve speed and not get build errors for such inconsequential problems!

**Comment by wooorm** [comment]
released in https://github.com/syntax-tree/hast-util-to-html/releases/tag/8.0.3!

**Comment by leafac** [comment]
Thank you very much for all your work, @wooorm 🙌
