### ISSUE TITLE
Add support to format the HTML in a tidy fashion

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/hast-util-to-html#29]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

It would be great if there is an option to specify formatting options, such as indenting.
using html-tidy or other tools is IMO overkill, as they parse the HTML again.

### Solution

have a minimal option: `indent` which will specify the number of spaces to use as [indent](https://api.html-tidy.org/tidy/quickref_5.8.0.html#indent).

### Alternatives

using a 3rd party html tidy tool. but this is overkill as it usually reparses the html.

**Comment by ChristianMurphy** [comment]
It sounds like you are looking for https://github.com/rehypejs/rehype-format ?

**Comment by ChristianMurphy** [comment]
They are independent and distinct, `rehype-format` handles indentation by modifying the AST, it does not change or configure `hast-util-to-html`

**Comment by tripodsan** [comment]
> They are independent and distinct, `rehype-format` handles indentation by modifying the AST, it does not change or configure `hast-util-to-html`

ah. ok. thanks.  I'll look into it.

**Comment by wooorm** [comment]
Added a note to [`rehype-stringify`](https://github.com/rehypejs/rehype/commit/3180c55d9102643e1321e50870469a975f4d1948). `rehype-format` already described the difference between it and `rehype-stringify`
