### ISSUE TITLE
`list-style-type` is stringified incorrectly

### ISSUE THREAD

**Issue by siefkenj** [syntax-tree/hast-util-to-html#30]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

```
toHtml(h("foo", {style: {"list-style-type": "'X'"}}))
```

### Expected behavior

```
<foo style="list-style-type: 'X'"></foo>
```

### Actual behavior

```
<foo style="list-style-type: &#x27;X&#x27;"></foo>
```

### Runtime

Node v16

### Package manager

npm v7

As per https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type  `list-style-type` should accept a quoted string as one of its possible values. However, if a quoted string is supplied, the quotes are escaped producing invalid CSS.

**Comment by wooorm** [comment]
Hey! This behavior is not wrong, those encoded apostrophes don’t change that they’re apostrophes!
If you want to control character references, you might want to use [`options.entities`](https://github.com/syntax-tree/hast-util-to-html#optionsentities), but again, you don’t have to, browsers understand this!
