### ISSUE TITLE
Add missing "type": "module" to package.json for Vite resolution

### ISSUE THREAD

**Issue by jorenbroekema** [syntax-tree/hast-util-to-html#32]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

- `import { toHtml } from 'hast-util-to-html'` in a JS file
- Run with Vite (e.g. dev server)
- 
![image](https://user-images.githubusercontent.com/36734656/176142859-67235a39-4a52-45d8-84eb-3c83d94ef499.png)

### Expected behavior

Some developer tools assume any module is a CommonJS module unless "type":"module" is specified in `package.json`.
I don't particularly agree with that approach and I'm not sure why the Vite maintainers decided to be more "dumb" about it in their resolution logic versus what they had before, but it seems to me that providing this meta information doesn't hurt and helps tools understand more clearly what format a module is.

Expected: "type": "module" in package.json

### Actual behavior

Missing "type": "module" in package.json, results in tools thinking the module is CommonJS format.

### Affected runtime and version

node@16.11.1

### Affected package manager and version

npm@8.5.2

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
https://github.com/syntax-tree/hast-util-to-html/blob/fa187494263aa1087ba1c307abce72b2413e452e/package.json#L28

Update your dependencies and built tools

**Comment by jorenbroekema** [comment]
Ah sorry, I read over it completely. 👍

**Comment by wooorm** [comment]
no problem!
