### ISSUE TITLE
missing whitespace in root node

### ISSUE THREAD

**Issue by milahu** [syntax-tree/hast-util-to-html#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-from-parse5 7.1.0
hast-util-to-html 8.0.3
parse5 7.1.1

### Link to runnable example

https://codepen.io/milahu/pen/eYKRmBW?editors=1010

### Steps to reproduce

```js
import {parse} from 'parse5'
import {fromParse5} from 'hast-util-from-parse5'
import {toHtml} from 'hast-util-to-html'

const source = `
<html>
  <head>
    <title>asdf</title>
  </head>
  <body>
    <div>asdf</div>
  </body>
</html>
`

function normalize(source) {
  const p5ast = parse(source, {
    sourceCodeLocationInfo: true,
  })
  const hast = fromParse5(p5ast)
  return toHtml(hast)
}

async function main() {

  console.log("input:")
  console.log(source)

  console.log("output:")
  console.log(normalize(source))
}

main()
```

### Expected behavior

```
<html>
  <head>
    <title>asdf</title>
  </head>
  <body>
    <div>asdf</div>
  </body>
</html>
```

### Actual behavior

```
<html><head>
    <title>asdf</title>
  </head>
  <body>
    <div>asdf</div>
  

</body></html>
```

### Affected runtime and version

not relevant

**Comment by wooorm** [comment]
This is required by the HTML standard, which we follow.
That behavior is not always useful. If you want pretty HTML, use `rehype-format`!
