### ISSUE TITLE
re: missing whitespace in root node

### ISSUE THREAD

**Issue by milahu** [syntax-tree/hast-util-to-html#34]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

https://github.com/syntax-tree/hast-util-to-html/issues/33

### Steps to reproduce

https://github.com/syntax-tree/hast-util-to-html/issues/33

> This is required by the HTML standard, which we follow.

so my input html is invalid?

```html
<!doctype html>
<html lang="en">
  <head>
    <title>test</title>
  </head>
  <body>
    <div>test</div>
  </body>
</html>
```

is valid html per https://validator.w3.org/nu/#textarea

the unified toolchain mangles this to

```html
<!doctype html><html lang="en"><head>
    <title>test</title>
  </head>
  <body>
    <div>test</div>
  

</body></html>
```

> the unified toolchain

i dont know where exactly the bug is.
maybe in hast-util-to-html, maybe somewhere else

> That behavior is not always useful.

its certainly useful for writing **lossless transformers**, which produce minimal diffs

maybe this could cause trouble in some tree consumers like [hast-util-select](https://github.com/syntax-tree/hast-util-select)
which expect "no whitespace in the root node"?

> If you want pretty HTML, use rehype-format!

no, i want to preserve the original whitespace

### Expected behavior

https://github.com/syntax-tree/hast-util-to-html/issues/33

### Actual behavior

https://github.com/syntax-tree/hast-util-to-html/issues/33

### Affected runtime and version

https://github.com/syntax-tree/hast-util-to-html/issues/33

**Comment by wooorm** [comment]
You can still comment on closed issues.

This isn’t about valid or invalid.
This is about the HTML standard prescribing how to parse HTML.
We follow how the HTML standards prescribes how to parse HTML.

We use an AST (abstract). Not a CST (concrete). We don’t generate the exact input document. We generate an equivalent document.

**Comment by milahu** [comment]
sorry .__.
please feel free to merge the issues

> We follow how the HTML standards prescribes how to parse HTML.

rendering html != transforming html

> We use an AST (abstract). Not a CST (concrete). We don’t generate the exact input document. We generate an equivalent document.

the parse tree is 99% concrete already.
it contains all the whitespce, except around the root node.
making it 100% concrete is a small fix with a large gain (at least for my use case).
at least this could be made optional

the resulting parser may be less "strict" and more "loose" than a perfectly spec-compliant parser ...
but so what? whats the punishment of breaking the spec?
except that html rendering is 0.1% slower, to skip some whitespace nodes

**Comment by wooorm** [comment]
> please feel free to merge the issues

That’s not possible through the GH UI, unfortunately!

> making it 100% concrete is a small fix 

It’s extremely complex. A concrete tree would house all original sources of character references. It would house whitespace inside tags. It would house the casing of attributes. It would include information on whether double or single quotes are used. It would information in doctypes, processing instructions. It would contain casing of tag names. It would be months of work to create.

> at least this could be made optional

It’s a ton of work, probably a full year to implement a new parser and design the data structure. If you are interested in paying me to make it reality I would likely quote you $200k.

> the resulting parser may be less "strict" and more "loose" than a perfectly spec-compliant parser ...

This project adheres to the HTML spec.

> whats the punishment of breaking the spec?

In this particular case of only the whitespace? It would indeed probably not be terribly complex to implement, but `parse5` doesn’t support it either. Feel free to investigate.

But we have had similar conversations about this: `hast` is for the HTML spec. If you want XML, use `xast`. If you want to use a different project that does not adhere to the spec, feel free to make it yourself.

**Comment by milahu** [comment]
thanks.

> feel free to make it yourself.

yes. i would use a concrete parser like

- [tree-sitter-html](https://github.com/tree-sitter/tree-sitter-html) with [treesitter-to-unist](https://github.com/hocdocsource/treesitter-to-unist)
- [lezer-parser-html](https://github.com/bmeurer/lezer-parser-html) to avoid WASM

with a different transformer (different node names, different data structure)
which is cheap, because my transformer is simple
