### ISSUE TITLE
Request more control over escaping

### ISSUE THREAD

**Issue by johnhooks** [syntax-tree/hast-util-to-html#35]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I'm using `toHtml` to stringify highlighted `code` elements and then use them in MDsveX, a Svelte version of MDX. Though I need to escape ```[{}`]``` because those are special characters in Svelte. I was attempting to escape them at the base of the AST on the text values. But I they were getting double escaped. I then figured out `toHtml` escapes `&`.

Currently, I'm running the hast through `toHTML` and then escaping the other characters I need. Though this seems brittle and also much less targeted than having control at the `Text.value` level.

### Solution

- make it possible to disable escaping in `toHtml`
- expose a `escape` option that allows overriding the default.

### Alternatives

- add the ability to add characters to `subset`

what do you think?

**Comment by wooorm** [comment]
This project focusses on standards, not on custom non-standard needs.

Disabling escaping would break everything. Allowing to override `escape` would break everything.

I don’t think this feature would be enough for you to generate a string for Svelte.
Also sounds like you don’t generate things for Svelte, but for MDsveX. Which is even more different.

What do you want to generate? Why use this project for that? Why not build your own project for Svelte/MDsveX’s format?
Why not use MDX itself, which also works with Svelte?

**Comment by johnhooks** [comment]
I am using this library to generate strings of html to highlight MDSveX fenced code blocks. I'm using `hastscript` to build the hast AST from [Shiki](https://shiki.matsu.io/) generated tokens. It's not necessarily generating anything MDsveX or Svelte specific, but since its processed by MDsveX after being generated, braces need to be escaped.

Everything is currently working beautifully, but I have to escaped `[{}`]` after calling `toHtml`. Like I said I thought adding `subset` would be better and wasn't sure why the option was disabled. I didn't believe I was inquiring on something that was non-standard, the ability to control which characters of a text value in HTML to escape seemed like it would be a common need.

**Comment by ChristianMurphy** [comment]
HTML and Svelte templates are related but different, I'd agree with @wooorm that this project focuses HTML, adding Svelte specific escapes doesn't make sense.
A pipeline which would likely make more sense for your use case.
* Start with the Shiki tokens
* Generate a `hast` tree
* Translate the `hast` tree to a `svast` tree https://github.com/pngwn/MDsveX/tree/master/packages/svast
* serialize the `svast` tree with `svast-stringify` https://github.com/pngwn/MDsveX/tree/master/packages/svast-stringify

Or alternatively:
* Start with the Shiki tokens
* Generate a `svast` tree
* Serialize the `svast` tree with `svast-stringify` https://github.com/pngwn/MDsveX/tree/master/packages/svast-stringify

In both cases, using `svast-stringify` should guarantee compatibly with MDsveX, since it is designed/built to implement MDsveX's own internal AST representation.

**Comment by johnhooks** [comment]
@ChristianMurphy and @wooorm thanks for the advice. I'll take a look at building a `svast` tree, rather than `hast`.

**Comment by johnhooks** [comment]
@ChristianMurphy or @wooorm, just to learn something new and more importantly, **if you have time** (otherwise disregard)...

Could you explain how more control over inserting HTML entities into the text content of the hast tree during stringification would break everything?

**Comment by johnhooks** [comment]
...sorry, I'm having trouble letting this go. Another reason for pushing, if I could get this to work, the highlighting library I'm writing could work as a general Rehype plugin in for highlighting code blocks with Shiki (Markdown, MDX, or MDsveX). This is the library I'm working on [@bitmachina/highlighter](https://github.com/johnhooks/highlighter), its inspired by [Rehype Pretty Code](https://github.com/atomiks/rehype-pretty-code), but this will also work with MDsveX. And I plan to make the code fence metadata parser more robust.

I can go a totally custom route, but the flexibility of `hast` and `hastscript` would really make this as flexible and customizable as possible.
