### ISSUE TITLE
Reduce dependencies size

### ISSUE THREAD

**Issue by korgan00** [syntax-tree/hast-util-to-html#38]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am working on a project using `unified`, `remark` and `rehype` and trying to improve deploying times I realized that the size of this dependency is huge because of `parse5`.
A let you part of the installation sizes.
<img width="1130" alt="Screenshot 2023-05-18 at 11 06 56 AM" src="https://github.com/syntax-tree/hast-util-to-html/assets/4138279/76193c1f-4520-44cd-b552-f87ecdfd09a6">

### Solution

Don't use parse5; try to replace it with another solution or use the unified system to parse.

### Alternatives

A custom parser.

**Comment by wooorm** [comment]
This project doesn't use parse5. Please check what this project does

**Comment by remcohaszing** [comment]
The question doesn’t clearly describe a problem to me, but I think you are looking for [`rehype-dom`](https://github.com/rehypejs/rehype-dom).

**Comment by korgan00** [comment]
Sorry about that, I was looking for [hast-util-from-html](https://github.com/syntax-tree/hast-util-from-html)

Thank you for the quick answer.
