### ISSUE TITLE
merge into hast-to-hyperscript, leveraging h2ml ?

### ISSUE THREAD

**Issue by derhuerst** [syntax-tree/hast-util-to-html#4]
[`h2ml`](https://github.com/jamen/h2ml) is one of several projects that generate HTML strings from the hyperscript syntax. I particularly like this one because it complies with [h2spec](https://github.com/hyper2/h2spec#h2spec-wip).

**Comment by wooorm** [comment]
One of the cool things about this projects is that it supports lots of settings, useful for prettyfying and minification (rehype-minify, rehype-format), and that project doesn't support this, right?

I like the spec though, and would love to make h support it!

**Comment by derhuerst** [comment]
fair point!

**Comment by wooorm** [comment]
I looked again at h2ml and it’s a nice project, it works well in the browser where space is a concern, but there’s a lot of ways HAST is better for its goals, namely being valid and optionally outputting tiny HTML.

1. h2ml can generate invalid HTML (no entity support)
2. h2ml doesn’t support comments or doctypes
3. h2ml can generate bloated HTML, hast-util-to-html can generate tiny HTML

...there’s definitely room for a tiny version of `hast-util-to-html` in the ecosystem that looks more like h2ml, but there’s also room for this project itself!
