### ISSUE TITLE
Possibility of configuring characters subset

### ISSUE THREAD

**Issue by skoropadas** [syntax-tree/hast-util-to-html#41]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want to be able to add/remove characters that should be escaped. I see that you have hard coded values [here](https://github.com/syntax-tree/hast-util-to-html/blob/9d7a2f7d63ec2d11b3ae5a5e4201181fdeedf6ea/lib/handle/text.js#L13), so I would like to be able to change them.

### Solution

Add the `subset` option to the list of all options, change the order for option assigning [here](https://github.com/syntax-tree/hast-util-to-html/blob/9d7a2f7d63ec2d11b3ae5a5e4201181fdeedf6ea/lib/handle/text.js#L37).

### Alternatives

I don't see any alternatives, I was trying to add my own plugin for rehype that escapes some symbols in text using HTML symbols, but it doesn't work because the symbol "&" is always escaped.

**Comment by ChristianMurphy** [comment]
Welcome @skoropadas 👋 

Taking a step back

> I want to be able to add/remove characters that should be escaped

Why? Characters need to be escaped to make HTML valid.
Producing invalid HTML seems like a non-goal?

> I was trying to add my own plugin for rehype that escapes some symbols in text using HTML symbols, but it doesn't work because the symbol "&" is always escaped.

I'm not sure I follow this, you don't want it to be escaped, so you can escape it anyway?

---

Reading between the lines this sounds very similar to past questions where an external platform didn't actually handle HTML correctly or trying to make non-HTML from HTML (recent example: https://github.com/syntax-tree/hast-util-to-html/issues/35)

If it is HTML related, open an issue with the platform for them to handle HTML.
If it is a non-HTML variant, you may want a different renderer or syntax tree.
